version: '3'
services:
  dc-full-stack-code-challenge-api:
    ports:
      - "8000:8080"
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/app
    environment:
      - PORT=8080
