version: '3'

networks:
  python-network:
  
services:
  # PostgreSQL service
  postgres:
    image: postgres
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    networks:
      python-network:
        aliases:
          - postgres-alias


  # Python application service
  dc-full-stack-code-challenge-api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: python_app
    environment:
      - DATABASE_URL=postgresql://postgres:root@db/code_challenge
    ports:
      - "8000:8000"
    volumes:
      - ../main.py:/app/main.py
    networks:
      - python-network

volumes:
  postgres_data:
